stories = [
    "A young boy named Jack was playing in the park when he heard a soft whimpering. He looked around and found a tiny puppy lost under a bench. Jack gently picked up the puppy and looked for its owner, but no one seemed to be around. He decided to take the puppy home and ask around the neighborhood. After two days, he finally found the puppy's owner, a little girl who had been searching everywhere. She was so happy that she hugged Jack and thanked him. Jack was glad he could help the puppy find its home.",

    "Lily was feeling down because her best friend Emma had moved to another city a month ago. It was her birthday, and she thought it would be lonely this year. However, when she came home from school, she was surprised to see a big box in the living room. Inside the box was Emma, who had come all the way to visit her! Lily was overjoyed, and they spent the entire weekend together. It turned out to be the best birthday surprise Lily could have asked for.",

    "Every morning, an old fisherman named Sam would go out to sea to catch fish. One day, despite fishing for hours, he caught nothing. As he was about to head back, he felt a strong pull on his fishing rod. After a tough struggle, he reeled in a giant fish. Sam had never seen such a large fish before. He proudly took it back to the village, where everyone was amazed. From that day on, Sam became known as the fisherman with the greatest catch.",

    "In a small village, there lived a poor boy named Tom who loved to paint. One day, he found a magical paintbrush that could bring anything he painted to life. He painted food for the hungry and houses for the homeless. Soon, everyone in the village heard about his magical talent and came to him for help. But Tom only used the paintbrush for good, never for selfish reasons. Thanks to his kindness, the village prospered, and everyone lived happily.",

    "There was once a goat that was very stubborn. Every day, the farmer tried to lead it to the pasture, but the goat always refused to go. One day, the goat saw all the other animals happily eating fresh grass in the field. It finally realized that the farmer only wanted what was best for it. From that day on, the goat followed the farmer obediently and enjoyed the lush green pastures. The farmer was happy, and so was the goat.",

    "A tiny squirrel named Nutty lived in the forest. One day, a big storm hit the forest, and the animals were scared. Nutty noticed that a baby bird had fallen from its nest and was in danger. Without hesitation, Nutty climbed the tallest tree to rescue the bird. Despite the strong winds, Nutty managed to put the bird back in its nest. The other animals praised Nutty for being so brave and courageous.",

    "Mrs. Smith was an elderly woman who lived alone in a small house. One winter, it snowed heavily, and she couldn’t leave her house to buy groceries. Her neighbor, a young man named John, noticed her struggle and decided to help. He shoveled her driveway and brought her food every day until the snow melted. Mrs. Smith was incredibly grateful and thanked John for his kindness. John realized that helping others made him feel good inside.",

    "Sarah was in a rush to leave the house when she realized she had lost her keys. She searched everywhere but couldn’t find them. Panicking, she called her friend Maria for help. Maria came over and suggested retracing Sarah’s steps. After a while, they found the keys inside the couch. Sarah was relieved and promised to be more careful in the future. Maria smiled and said, 'Sometimes the solution is right in front of us.'",

    "A little girl named Mia loved gazing at the stars. Every night, she would sit by her window and wonder what it would be like to visit space. One day, her teacher announced a school competition where the winner would get to visit a space museum. Mia worked hard on her project about the planets and won first place. She visited the museum, saw rockets up close, and even met an astronaut. Mia realized that dreams could come true with hard work and determination.",

    "Mr. Green loved gardening and had a beautiful garden full of colorful flowers. However, one summer, a terrible drought hit the town, and most of his plants withered. Mr. Green was heartbroken but refused to give up. He started collecting rainwater and carefully tended to the remaining plants. Over time, his garden slowly came back to life. The neighbors admired his perseverance, and Mr. Green's garden became a symbol of hope in the community.",

    "Max and Ruby were two adventurous siblings who loved exploring the forest near their home. One day, while walking, they found a hidden path that led to a secret waterfall. They were amazed by the beauty of the place and decided to keep it as their special spot. They visited the waterfall every week and even brought a picnic. It became their favorite place to relax and enjoy nature.",

    "In a faraway village, there was a gentle giant who lived in the mountains. The villagers were afraid of him because of his size, but one day, he saved a child who had fallen into the river. After that, the villagers realized the giant was kind and not to be feared. They invited him to join their festivals, and he became a beloved member of the community. The giant was happy to have found new friends.",

    "One day, a hungry fox spotted a bunch of grapes hanging from a vine. He jumped and jumped but couldn’t reach them. Frustrated, he finally gave up and walked away, telling himself that the grapes were probably sour anyway. Later, the fox realized that sometimes, when we can’t get what we want, it’s easy to pretend we never wanted it in the first place. The fox learned that patience and effort are key to success.",

    "Emily loved reading books more than anything else. She would spend hours in the library, lost in different stories. One day, she discovered an old, dusty book tucked away on a shelf. It turned out to be a magical book that could transport her into the story. Emily had many exciting adventures inside the book, but in the end, she always returned to her real world. She learned that reading can take you anywhere, even if you never leave your room.",

    "Tom had always wanted a bike, but his parents couldn’t afford one. He decided to save money by doing odd jobs around the neighborhood. After months of hard work, Tom finally had enough money to buy the bike. The day he brought it home was one of the happiest days of his life. He realized that working hard for something made it even more special. Tom loved riding his new bike every day and took great care of it."
]

qna = [
    "What is the capital of France?",
    "How many days are there in a week?",
    "What is the boiling point of water?",
    "Which planet is known as the Red Planet?",
    "What is the largest mammal in the world?",
    "What is the square root of 64?",
    "What currency is used in Japan?",
    "What is the national animal of India?",
    "What gas do plants absorb from the atmosphere?",
    "Who wrote the play 'Romeo and Juliet'?",
    "What is the fastest land animal?",
    "What is the chemical symbol for water?",
    "Who was the first man to walk on the moon?",
    "How many continents are there?",
    "What is the main ingredient in guacamole?",
    "What is the tallest mountain in the world?",
    "Which country hosted the 2016 Summer Olympics?",
    "What is the chemical symbol for gold?",
    "What is the freezing point of water?",
    "Who is known as the 'Father of Computers'?",
    "Which fruit is known as the 'king of fruits'?",
    "How many colors are there in a rainbow?",
    "Who discovered gravity?",
    "Which ocean is the largest?",
    "How many letters are there in the English alphabet?",
    "Which metal is used to make airplanes?",
    "Who was the first President of the United States?",
    "What is the largest planet in our solar system?",
    "How many bones are there in the human body?",
    "What is the capital of Italy?",
    "What is the main ingredient in sushi?",
    "Which country is known for inventing the pizza?",
    "What is the longest river in the world?",
    "Who painted the Mona Lisa?",
    "What is the hardest natural substance on Earth?",
    "How many hours are there in a day?",
    "What is the speed of light?",
    "What language do they speak in Brazil?",
    "Who was the first woman to win a Nobel Prize?",
    "How many planets are in the solar system?",
    "What is the largest desert in the world?",
    "Which bird is a symbol of peace?",
    "Which country is known as the Land of the Rising Sun?",
    "What is the largest organ in the human body?",
    "Which animal is known as the 'Ship of the Desert'?",
    "How many teeth does an adult human have?",
    "What is the chemical symbol for oxygen?",
    "Which planet is closest to the sun?",
    "What is the smallest country in the world?",
    "Which animal is known for changing its color?",
    "What do bees collect from flowers?",
    "Who invented the telephone?",
    "What is the national language of Canada?",
    "Which element is found in all organic compounds?",
    "What is the longest bone in the human body?",
    "What is the most common gas in Earth's atmosphere?",
    "What is the hardest part of the human body?",
    "Which is the largest species of shark?",
    "What is the name of the highest waterfall in the world?",
    "Which bird can mimic human speech?",
    "Which city is known as the Big Apple?",
    "What is the smallest bone in the human body?",
    "What is the main ingredient in chocolate?",
    "How many time zones are there in the world?",
    "What is the most popular sport in the world?",
    "Who was the first person to win two Nobel Prizes?",
    "Which country produces the most coffee in the world?",
    "How many muscles are there in the human body?",
    "What is the national sport of Canada?",
    "Who is the author of 'Harry Potter' series?",
    "What is the process by which plants make food?",
    "Which planet has the most moons?",
    "What is the most common blood type?",
    "What is the capital of Australia?",
    "Which instrument has 88 keys?",
    "What type of animal is a Komodo dragon?",
    "How many stripes are there on the American flag?",
    "What is the largest island in the world?",
    "Which continent is known as the 'Dark Continent'?",
    "What is the national flower of Japan?",
    "What is the smallest unit of life?",
    "Which vitamin is produced when a person is exposed to sunlight?",
    "Which country gave the Statue of Liberty to the USA?",
    "Which animal is known as man's best friend?",
    "Which country is the largest producer of rice?",
    "How many wheels does a tricycle have?",
    "What is the national sport of Japan?",
    "What is the currency of the United Kingdom?",
    "What is the first element on the periodic table?",
    "Which planet is known as Earth's twin?",
    "Which element is needed for combustion to occur?",
    "What do caterpillars turn into?",
    "Who is the author of 'The Theory of Relativity'?",
    "Which sea creature has three hearts?",
    "Which country invented paper?",
    "What is the most common type of tree in the world?",
    "How many wings does a bee have?",
    "What is the fear of spiders called?",
    "Which planet is known for its rings?",
    "What is the name of the first artificial satellite sent into space?",
    "Which animal is the largest primate?"
]

jumbled = [
    ("held at", "The meeting", "10 AM", "will be", "in the conference room."),
    ("hiking in", "She enjoys", "during the summer", "the mountains."),
    ("completed by", "is expected", "The new project", "next month", "to be."),
    ("Learning a", "can open", "second language", "many opportunities."),
    ("station exactly", "The train", "arrived at", "on time.", "the"),
    ("growth and success", "drives", "Innovation", "in any organization."),
    ("reviewed the", "He carefully", "before submitting it", "report", "to the manager."),
    ("She traveled", "for a", "to Paris", "business meeting", "last week."),
    ("a new", "next quarter", "The company", "is launching", "product line."),
    ("Effective communication", "is crucial", "professional setting.", "in any"),
    ("is working", "He", "that explores", "on a research project", "artificial intelligence."),
    ("presented a", "The marketing team", "detailed campaign", "strategy."),
    ("Our customer", "available 24/7", "for assistance.", "service department is"),
    ("The team", "ahead of schedule.", "successfully completed", "the project"),
    ("heavy rain", "The weather forecast", "predicts", "over the weekend."),
    ("She prepared", "a presentation", "board of directors.", "for the"),
    ("is planning", "to expand", "The company", "internationally.", "its operations"),
    ("Reading regularly", "can improve", "comprehension.", "your vocabulary and"),
    ("He received", "for his", "a promotion", "excellent performance", "at work."),
    ("a charity event", "They organized", "to raise funds", "for a", "good cause."),
    ("was busy", "The airport", "heading to various destinations.", "with travelers"),
    ("about environmental", "She is passionate", "and sustainability.", "conservation"),
    ("working on", "They are", "to reduce", "a solution", "carbon emissions."),
    ("his flight", "He booked", "and hotel", "for the upcoming", "conference."),
    ("submitted her", "before the deadline.", "The student", "assignment"),
    ("on this project", "for over", "Our team", "has been working", "six months."),
    ("several bugs", "The software update", "and improved performance.", "fixed"),
    ("is responsible", "He", "for managing", "the company's finances."),
    ("The restaurant", "excellent reviews", "received", "for its new menu."),
    ("an international firm", "They collaborated", "on this", "initiative.", "with"),
    ("She conducted", "research on", "extensive", "the topic", "for her thesis."),
    ("key findings", "highlights the", "The report", "of the investigation."),
    ("He is looking forward", "to attending", "the training workshop", "next week."),
    ("a grand event.", "celebrated its", "The company", "tenth anniversary", "with"),
    ("has been working", "She", "since the start", "remotely", "of the pandemic."),
    ("will take place", "The system upgrade", "during the weekend.", ""),
    ("completed an advanced course", "He recently", "in project management."),
    ("improve employee satisfaction", "The new policy", "aims to", "and productivity."),
    ("learning how to code", "She is", "for her new job.", "in Python"),
    ("organized a virtual meeting", "They", "to discuss", "the project’s", "progress.")
]

repeating = [
    "Please call me back when you have the time.",
    "The presentation was scheduled for next Monday.",
    "I will send the documents by the end of the day.",
    "She is working hard to finish the project on time.",
    "The report needs to be submitted by tomorrow afternoon.",
    "We should schedule a meeting for next week.",
    "The new software update has several useful features.",
    "Can you share the data with the team by Friday?",
    "Our team is working on multiple projects this month.",
    "He was excited to start his new job at the company.",
    "The weather forecast predicts rain for the weekend.",
    "Her performance during the interview was exceptional.",
    "I will check the calendar and let you know my availability.",
    "The marketing team is planning a new campaign.",
    "The product launch event was a huge success.",
    "They are considering expanding the business internationally.",
    "We are expecting the shipment to arrive by next week.",
    "He is working late to meet the project deadline.",
    "The client is requesting a detailed progress report.",
    "She attended a conference on artificial intelligence last month.",
    "Please make sure to follow up with the customer tomorrow.",
    "They are organizing a training session for the new employees.",
    "The team is preparing for the quarterly business review.",
    "The hotel reservations have been confirmed for your stay.",
    "He sent the invitation for the meeting via email.",
    "Our new product line will be available in stores next month.",
    "They are developing a new feature for the mobile app.",
    "The company is investing in research and development.",
    "She presented her findings at the annual conference.",
    "The flight was delayed due to bad weather conditions.",
    "We have scheduled the interview for next Thursday.",
    "He is responsible for managing the company's finances.",
    "They are working on a solution to improve the system’s performance.",
    "I received an update on the progress of the project today.",
    "The event will be held at the main auditorium at 6 PM.",
    "She is organizing a team-building activity next weekend.",
    "The customer service department handles all inquiries.",
    "He is preparing a report on the current market trends.",
    "The CEO will be addressing the employees later this afternoon.",
    "We have finalized the budget for the next financial year."
]

reading = [
    "The meeting will be held at 10 AM in the conference room.",
    "She enjoys hiking in the mountains during the summer.",
    "The new project is expected to be completed by next month.",
    "Learning a second language can open many opportunities.",
    "The train arrived at the station exactly on time.",
    "Innovation drives growth and success in any organization.",
    "He carefully reviewed the report before submitting it to the manager.",
    "She traveled to Paris for a business meeting last week.",
    "The company is launching a new product line next quarter.",
    "Effective communication is crucial in any professional setting.",
    "He is working on a research project that explores artificial intelligence.",
    "The marketing team presented a detailed campaign strategy.",
    "Our customer service department is available 24/7 for assistance.",
    "The team successfully completed the project ahead of schedule.",
    "The weather forecast predicts heavy rain over the weekend.",
    "She prepared a presentation for the board of directors.",
    "The company is planning to expand its operations internationally.",
    "Reading regularly can improve your vocabulary and comprehension.",
    "He received a promotion for his excellent performance at work.",
    "They organized a charity event to raise funds for a good cause.",
    "The airport was busy with travelers heading to various destinations.",
    "She is passionate about environmental conservation and sustainability.",
    "They are working on a solution to reduce carbon emissions.",
    "He booked his flight and hotel for the upcoming conference.",
    "The student submitted her assignment before the deadline.",
    "Our team has been working on this project for over six months.",
    "The software update fixed several bugs and improved performance.",
    "He is responsible for managing the company's finances.",
    "The restaurant received excellent reviews for its new menu.",
    "They collaborated with an international firm on this initiative.",
    "She conducted extensive research on the topic for her thesis.",
    "The report highlights the key findings of the investigation.",
    "He is looking forward to attending the training workshop next week.",
    "The company celebrated its tenth anniversary with a grand event.",
    "She has been working remotely since the start of the pandemic.",
    "The system upgrade will take place during the weekend.",
    "He recently completed an advanced course in project management.",
    "The new policy aims to improve employee satisfaction and productivity.",
    "She is learning how to code in Python for her new job.",
    "They organized a virtual meeting to discuss the project’s progress."
]

hr = [
    "What motivates you to perform your best?",
    "How do you handle stress and pressure?",
    "Can you describe a challenging situation you faced and how you overcame it?",
    "What are your greatest strengths and weaknesses?",
    "How do you prioritize your tasks when managing multiple deadlines?",
    "What is your favorite project you have worked on and why?",
    "How do you approach teamwork and collaboration?",
    "What is a skill you would like to improve and how do you plan to do it?",
    "How do you stay organized in your work?",
    "What are your long-term career goals?",
    "How do you handle constructive criticism?",
    "Can you describe a time when you took the initiative?",
    "What role do you usually take in team projects?",
    "How do you adapt to changes in the workplace?",
    "What do you believe is the key to effective communication?",
    "How do you balance work and personal life?",
    "What do you consider to be your biggest achievement?",
    "How do you keep yourself motivated during repetitive tasks?",
    "What steps do you take to ensure your work is of high quality?",
    "How do you celebrate your successes?",
    "What makes you unique as a candidate?"
]
